#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * ============================================================================
 * Projet      : Projet Robot EV3
 * Fichier     : projet.c
 * Description : Programme de commande du robot EV3
 *
 * Auteur       : Houssam BACAR
 * Formation    : M2 ILIADE
 * Établissement: UBO
 * Date         : 30/09/2026
 * Version      : 1.0
 *
 * Matériel :
 * - Robot LEGO Mindstorms EV3
 * - Moteurs : ports B et C
 * -  : port 4 : Gyro
 * -  : port 1 : Touch
 *
 * Fonctionnement :
 * Voir le fichier : Robot > Lego Bricks > File Management Utility > rc-data > ... (select a file here) > upload
 *
 * ============================================================================
 */




 int min = 0;
 int max = 0;

 //Variables  et constantes

#define MIN_POWER  5
#define MAX_SPEED  143


int puissances[100];



void motorCharacterization()
{
		int sens = 1;

		int puissance = 0;

		//long prev;
		long current;

		//delay (600);

		current = nSysTime;


		int active = 0;

		//"projet_puissan.txt"
		string  filename = "temp.txt";


		long  fileHandle = fileOpenWrite (filename);


  	string puis = "puissance rpm \n";

  	fileWriteData( fileHandle, puis, strlen (puis) );


		while( getButtonPress(buttonEnter) == 0 && !active )

		{

				puissances[puissance] = getMotorRPM( A_moteur );

				stringFormat( puis, "\n %d  %d \n", puissance , puissances[puissance]);

  			fileWriteData( fileHandle, puis, strlen (puis) );

				if(getButtonPress(buttonUp) == 1)
				{
					if(puissance < 100)
					{
						puissance += 1;
					}
					//Si on met pas ceci, ça n'arrive pas à detecter l'appui : c'est trop rapide.
					while( getButtonPress(buttonUp) == 1 ){}
				}
				else
				if( getButtonPress(buttonDown) == 1)
				{
						if(puissance > 0)
					{
						puissance -= 1;
					}

					while( getButtonPress(buttonDown) == 1 ){}
				}
				else
				if( getButtonPress(buttonLeft) == 1)
				{
						if(sens == 1)
						{
								sens = -1;
						}

						while( getButtonPress(buttonLeft) == 1 ){}
				}
				else
				if( getButtonPress(buttonRight) == 1)
				{
						if(sens == -1)
						{
								sens = 1;
						}

						while( getButtonPress(buttonRight) == 1 ){}
				}

				setMotorSpeed( motorA , puissance * sens );
				delay (100);
				puissance += 1;

				if (puissance >= 100) {active = 1;}

		}



		setMotorSpeed( motorA , 0 );


		fileClose( fileHandle );

  stopAllTasks ();

}

void launchMotorSpeed(int speed)
{
	  int speed_abs;

	  speed_abs = fabs(speed);

	  if ( speed_abs > MAX_SPEED )
	  {
	  		setMotorSpeed( motorA , MAX_SPEED );

	  } else if ( speed_abs < MIN_POWER )
	  {
	  		setMotorSpeed( motorA , MIN_POWER );
	  }

}

task main()
{
		motorCharacterization();
}
