#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * ============================================================================
 * Projet      : Projet Robot EV3
 * Fichier     : projet.c
 * Description : Programme de commande du robot EV3
 *
 * Auteur       : Houssam BACAR
 * Formation    : M2 ILIADE
 * Établissement: UBO
 * Date         : 30/09/2026
 * Version      : 1.0
 *
 * Matériel :
 * - Robot LEGO Mindstorms EV3
 * - Moteurs : ports B et C
 * -  : port 4 : Gyro
 * -  : port 1 : Touch
 *
 * Fonctionnement :
 * Voir le fichier : Robot > Lego Bricks > File Management Utility > rc-data > ... (select a file here) > upload
 *
 * ============================================================================
 */




 int min = 0;
 int max = 0;

 //Variables  et constantes

#define MIN_POWER  5
#define MAX_SPEED  143

#define PENTE 1.71

#define TACHE_ACTIVE 1

int puissances[100];

int cap_degree;

int correction;

TSemaphore capMotorMutex;

task keepHeading()
{
	int position_reel;

	int erreur;

	while ( TACHE_ACTIVE )
 	{
		// TODO
 	  position_reel =  getMotorEncoder(motorA);

 	  erreur = cap_degree - position_reel;

 	  if (erreur != 0)
  	{
  		correction = erreur;
  	}
	}
}



void motorCharacterization()
{
		int sens = 1;

		int puissance = 0;

		//long prev;
		long current;

		//delay (600);

		current = nSysTime;


		int active = 0;

		//"projet_puissan.txt"
		string  filename = "temp.txt";


		long  fileHandle = fileOpenWrite (filename);


  	string puis = "puissance rpm \n";

  	fileWriteData( fileHandle, puis, strlen (puis) );

  	int puissanceConstante = 20;

  	int degree = 0;

  	cap_degree = 0;
		resetMotorEncoder( motorA );

		startTask ( keepHeading );


		while( getButtonPress(buttonEnter) == 0  )
		{
				if(getButtonPress(buttonUp) == 1)
				{
					degree =  90;
					semaphoreLock ( capMotorMutex );

					cap_degree += degree + correction;

					semaphoreUnlock (capMotorMutex);

					setMotorTarget( motorA , cap_degree, puissanceConstante);
					//Si on met pas ceci, ça n'arrive pas à detecter l'appui : c'est trop rapide.
					while( getButtonPress(buttonUp) == 1 ){}
				}
				else
				if( getButtonPress(buttonDown) == 1)
				{
					degree = -90;
					semaphoreLock ( capMotorMutex );

					cap_degree += degree + correction;

					semaphoreUnlock (capMotorMutex);
					setMotorTarget( motorA , cap_degree, puissanceConstante);
					while( getButtonPress(buttonDown) == 1 ){}
				}
				else
				if( getButtonPress(buttonLeft) == 1)
				{
						degree = -10;
						semaphoreLock ( capMotorMutex );

						cap_degree += degree + correction;

						semaphoreUnlock (capMotorMutex);
						setMotorTarget( motorA , cap_degree, puissanceConstante);
						while( getButtonPress(buttonLeft) == 1 ){}
				}
				else
				if( getButtonPress(buttonRight) == 1)
				{
						degree = 10;
						semaphoreLock ( capMotorMutex );

						cap_degree += degree + correction;

						semaphoreUnlock (capMotorMutex);
						setMotorTarget( motorA , cap_degree, puissanceConstante);
						while( getButtonPress(buttonRight) == 1 ){}
				}

				//delay (100);
				//puissance += 1;

				if (puissance >= 100) {active = 1;}

		}

		setMotorSpeed( motorA , 0 );


		fileClose( fileHandle );

  stopAllTasks ();

}




void launchMotorSpeed(int speed)
{
	  int speed_abs;

	  speed_abs = fabs(speed);

	  if ( speed_abs > MAX_SPEED )
	  {
	  		setMotorSpeed( motorA , MAX_SPEED );

	  } else if ( speed_abs < MIN_POWER )
	  {
	  		setMotorSpeed( motorA , MIN_POWER );
	  }else
		{
			  setMotorSpeed( motorA , speed / PENTE );
		}
}

task main()
{
	semaphoreInitialize ( capMotorMutex );
		motorCharacterization();

		while (TACHE_ACTIVE){}
}
