#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{


int nSpeed = 20;
int nMSecA = 4000;

setMotorSpeed(motorA, nSpeed);
//sleep(nMSecA);
delay(nMSecA);

setMotorSpeed(motorA, 0);

}
