#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{


int sens=1;
int nSpeed = 20;
int nMSecA = 3000;

int action = -1;
bool getOut = false;

int timerA;
resetBumpedValue(S1);
while(getButtonPress(buttonEnter)==0  || !getOut){

	timerA =  getMicroTimer();

	int differential = timerB - timerA;
	//Routable sens
  if(differential >= 0.0f && differential <= 0.5f){
  			eraseDisplay();
  			action = 1;
  }

	if (getBumpedValue(SensorTouch1)>0){
		timerB =  getMicroTimer();
	}

	switch(action) {
	 	case 1 : getOut = false;
	 	break;
		default :{
	 				sens = -sens;
		setMotorSpeed(motorA, nSpeed * sens);
		//delay(nMSecA);

	}
  }
  resetBumpedValue(SensorTouch1);
}

}
