#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * ============================================================================
 * Projet      : Robot EV3
 * Fichier     : ex3_corrects.c
 * Description : Programme de commande du robot EV3
 *
 * Auteur       : Houssam BACAR
 * Formation    : M2 ILIADE
 * Établissement: UBO
 * Date         : 28/09/2026
 * Version      : 1.0
 *
 * Matériel :
 * - Robot LEGO Mindstorms EV3
 * - Moteurs : ports B et C
 * - Capteur ultrasonique : port 4
 * - Capteur tactile : port 1
 *
 * Fonctionnement :
 * Ce programme permet au robot de se déplacer et d'éviter
 * les obstacles détectés par le capteur ultrasonique.
 *
 * ============================================================================
 */


task main()
{
		int sens = 1;

		long prev;
		long current;

		delay (600);

		current = nSysTime;

		while(1)
		{
				if(getTouchValue(SensorTouch1) == 1)
				{
						setMotorSpeed( motorA , 20 * sens );
						sens 		= -1 * sens;
						prev 		= current;
						current = nSysTime;
						while(getTouchValue(SensorTouch1)==1){}
				}
		}

}
