#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * ============================================================================
 * Projet      : Robot EV3
 * Fichier     : ex4_corrects.c
 * Description : Programme de commande du robot EV3
 *
 * Auteur       : Houssam BACAR
 * Formation    : M2 ILIADE
 * Établissement: UBO
 * Date         : 28/09/2026
 * Version      : 1.0
 *
 * Matériel :
 * - Robot LEGO Mindstorms EV3
 * - Moteurs : ports B et C
 * -  : port 4
 * -  : port 1
 *
 * Fonctionnement :
 *
 *
 * ============================================================================
 */


task main()
{
		int sens = 1;
		int puissance = 0;

		long prev;
		long current;

		delay (600);

		current = nSysTime;

		while(getButtonPress(buttonEnter) == 0)
		{
				if(getButtonPress(buttonUp) == 1)
				{
						puissance += 10;

				}
				else
				if(getButtonPress(buttonDown) == 1)
				{
						puissance -= 10;


				}
				else
				if(getButtonPress(buttonLeft) == 1)
				{
						if(sens == -1)
						{
								sens = 1;
						}
				}
				else
				if(getButtonPress(buttonRight) == 1)
				{
						if(sens == 1)
						{
								sens = -1;
						}

				}

				setMotorSpeed( motorA , puissance * sens );
		}

		setMotorSpeed( motorA , 0 );

}
