#pragma config(Sensor, S1,     SensorTouch1,   sensorEV3_Touch)
#pragma config(Sensor, S4,     SensorGyro4,    sensorEV3_Gyro)
#pragma config(Motor,  motorA,          A_moteur,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{


int sens=1;
resetBumpedValue(S1);
while(getButtonPress(buttonEnter)==0){
	if (getBumpedValue(S1)>0){
		break;
	}
}


int nSpeed = 20;
int nMSecA = 3000;

setMotorSpeed(motorA, nSpeed);
sleep(nMSecA);
delay(nMSecA);
setMotorSpeed(motorA, 0);
delay(nMSecA);
delay(nMSecA);
int nMSecB = 4000;
setMotorSpeed(motorA, -nSpeed);
//sleep(nMSec);
delay(nMSecA);
setMotorSpeed(motorA, -10);
sleep(2000);
delay(1000);
setMotorSpeed(motorA, 0);

}
